Name:           ros-indigo-nj-oa-costmap
Version:        0.1.1
Release:        0%{?dist}
Summary:        ROS nj_oa_costmap package

Group:          Development/Libraries
License:        BSD
URL:            http://wiki.ros.org/nj_oa_laser
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-indigo-geometry-msgs
Requires:       ros-indigo-lama-jockeys
Requires:       ros-indigo-map-ray-caster
Requires:       ros-indigo-nav-msgs
Requires:       ros-indigo-nj-oa-laser
Requires:       ros-indigo-roscpp
Requires:       ros-indigo-tf
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-geometry-msgs
BuildRequires:  ros-indigo-lama-jockeys
BuildRequires:  ros-indigo-map-ray-caster
BuildRequires:  ros-indigo-nav-msgs
BuildRequires:  ros-indigo-nj-oa-laser
BuildRequires:  ros-indigo-roscpp
BuildRequires:  ros-indigo-tf

%description
The nj_oa_costmap package is a navigating jockey for the Large Maps framework.
Its role is to drive the robot forward while avoiding obstacles. It uses a local
map which position is relative to the robot but which orientation is constant.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Tue Jan 20 2015 Gaël Ecorchard <gael.ecorchard@ciirc.cvut.cz> - 0.1.1-0
- Autogenerated by Bloom

